### ISSUE TITLE
Specify what to show when < 2 reviews are available

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#10]
- [ ] Article teaser shows `N reviews`. This text doesn't make sense if there is 0 reviews or 1 _review_ around.
- [ ] Article teaser shows the most recent review. In case there are 0 reviews, the behavior is undefined.

**Comment by chugginselifesciences** [comment]
0 reviews - listing when first version published
![image](https://user-images.githubusercontent.com/41907215/80586248-93ac3a80-8a0c-11ea-9602-619d5920d78d.png)

0 reviews - listing when updated/new version
![image](https://user-images.githubusercontent.com/41907215/80586534-ff8ea300-8a0c-11ea-8a5c-fa09dbc5f8fc.png)


1 review - when review is added:
![image](https://user-images.githubusercontent.com/41907215/80586221-8a22d280-8a0c-11ea-9806-197576cf6745.png)


2+ reviews - when review is added
![image](https://user-images.githubusercontent.com/41907215/80586318-ae7eaf00-8a0c-11ea-9434-c8670d3196c8.png)


reviewed and updated
![image](https://user-images.githubusercontent.com/41907215/80586482-ee459680-8a0c-11ea-92b2-17bd6d582df8.png)
