### ISSUE TITLE
Investigate not found intermittent problems

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#101]
e.g. on http://prc-staging.libero.pub/articles/10.1101/642017

This used to be a 404 coming from DataCite, but schema.org could also be having problems.

**Comment by giorgiosironi** [comment]
Locally I get:
```
2020-05-20T12:32:56.836Z app:middleware:fetch-reviews-for-article-page Failed to load reviews for article 10.1101/615682: (jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.)
```
May be a red-herring or not.

**Comment by thewilkybarkid** [comment]
Think it's https://github.com/schemaorg/schemaorg/issues/2578 (Schema.org content negotiation isn't working).

**Comment by thewilkybarkid** [comment]
The DataCite JSON-LD usage references the Schema.org context, so has to be requested at runtime (unless it is hard-coded locally).

https://support.datacite.org/docs/datacite-content-resolver suggests `text/turtle` and `application/rdf+xml` are supported, but neither does: the former sends you to the real content (wrong, should be a `406 Not Acceptable` if it isn't supported), and the latter returns a `422 Unprocessable Entity` (also wrong).

**Comment by thewilkybarkid** [comment]
So, neither DataCite nor Crossref have particularly usable RDF. Only thing to do now is request their own formats (`application/vnd.crossref.unixref+xml` and `application/vnd.datacite.datacite+xml`).

**Comment by thewilkybarkid** [comment]
For quick mitigation, looking at hard-coding the Schema.org context locally.

**Comment by thewilkybarkid** [comment]
Alternative is to request `application/vnd.codemeta.ld+json` rather than `application/vnd.schemaorg.ld+json`, which using a remote context on GitHub. Still just short-term mitigation.
