### ISSUE TITLE
Article page - content header - grid layout

### ISSUE THREAD

**Issue by chugginselifesciences** [libero/prc#102]
Make 2 columns and move "review list" to the 2nd column - should be a 5 to 1 split with 48px right margin on left column/title and authors.

![image](https://user-images.githubusercontent.com/41907215/82454672-f0e65980-9aa9-11ea-9e92-8c93edd35802.png)

**Comment by davidcmoulton** [comment]
@chugginselifesciences At narrower widths should the reviews list appear beneath the DOI?

**Comment by chugginselifesciences** [comment]
Yes it seems like the best option to me.

**Comment by davidcmoulton** [comment]
@chugginselifesciences Like this?

![article-header-grid](https://user-images.githubusercontent.com/2893480/82538032-ff348400-9b42-11ea-8a64-23ea384b5c80.gif)

(Breakpoint is 900px, same as the others on the page. Not worrying about tuning those at the moment.)

**Comment by chugginselifesciences** [comment]
Yes, looks good thanks David.

My previous designs made use of the grid for larger margins at the side of the screen but we can worry about that another day.

e.g. It would be better if we brought content in 1 column from 1200px down to 900px. This is an example at 900px. But not to worry about now. We can talk more about responsive behaviour soon.

![image](https://user-images.githubusercontent.com/41907215/82538702-0c05a780-9b44-11ea-8d3d-dbc1e9d87525.png)
