### ISSUE TITLE
Centre Homepage title and subtitle

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#104]

**Comment by giorgiosironi** [comment]
Is this the desired result?
![Screenshot_2020-05-21 Untitled Publish Review Curate Platform](https://user-images.githubusercontent.com/160299/82538203-46227980-9b43-11ea-961e-e73a5442e12c.png)

**Comment by giorgiosironi** [comment]
Assuming it doesn't affect the titles in the [editorial community pages](http://prc-staging.libero.pub/editorial-communities/10360d97-bf52-4aef-b2fa-2f60d319edd7) and in the [article pages](http://prc-staging.libero.pub/articles/10.1101/642017).

**Comment by hdrury1** [comment]
Just updated the title of the ticket, @giorgiosironi. Would be good to centre the subtitle too:

<img width="697" alt="Screenshot 2020-05-21 at 09 15 06" src="https://user-images.githubusercontent.com/17023702/82538402-9d284e80-9b43-11ea-98a2-e28e6ba752d1.png">

**Comment by giorgiosironi** [comment]
Available in staging. Would check at different viewport sizes. Close if satisfied.

**Comment by giorgiosironi** [comment]
Should have a line break then?

**Comment by giorgiosironi** [comment]
In staging.
