### ISSUE TITLE
Add subtitle to homepage

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#110]
We should add a subtitle to the homepage to provide additional context for user testing:

"An experimental platform for multiple communities to provide post-publication peer review of scientific research. Learn more about the platform."

'Learn more about the platform' should link to the About page.

**Comment by giorgiosironi** [comment]
I used a `<p>` and added no style other than the default, anyone feel free to improve on it. Shortly available in staging.

**Comment by hdrury1** [comment]
Styling we can improve later depending on how quickly we deplete To Do

**Comment by giorgiosironi** [comment]
Available in staging.
