### ISSUE TITLE
Introduce Google Analytics

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#123]
@hdrury1 for direction. Probably a completely independent account from eLife?

**Comment by hdrury1** [comment]
I would agree, but not sure in principle how we should go about setting this up. @BlueReZZ can you give some options?

**Comment by giorgiosironi** [comment]
Yes I'm a bit wary of registering a PRC account with a `prc-admin@elifesciences.org` email address, and then all the naming changes.

**Comment by BlueReZZ** [comment]
> Yes I'm a bit wary of registering a PRC account with a `prc-admin@elifesciences.org` email address, and then all the naming changes.

Of that email only the `prc` part would infer any name. Why not register it with your personal account since the account management is based on individuals anyway and you can just give us all access? We can then add in a more general admin account when we have a `admin@untitledprcplatform.ly`

**Comment by hdrury1** [comment]
I've created an account. Giving access to the team now.

**Comment by giorgiosironi** [comment]
I assume we will have:

- no tracking in development environments
- tracking in `prod`
- a different tracking in `staging` (checking how to isolate the two) for testing purposes

**Comment by giorgiosironi** [comment]
@hdrury1 while I add this to `prod`, can you add a separate property for `staging` (if that's the best way to separate them)?

**Comment by giorgiosironi** [comment]
Starting by adding commented-out (hopefully) GA `<script>` tags as I can't test locally on this connection.

**Comment by giorgiosironi** [comment]
GA active on `staging` but not deployed to `prod` yet. Having it checked first.

**Comment by giorgiosironi** [comment]
We now have two GA properties, `staging` and `prod`.

**Comment by giorgiosironi** [comment]
For reference, [`All Pages` report on `prod`](https://analytics.google.com/analytics/web/?authuser=1#/report/content-pages/a167311475w233457116p219087825/_u.date00=20200521&_u.date01=20200521&explorer-table.plotKeys=%5B%5D&explorer-table-dataTable.sortColumnName=analytics.pageviews&explorer-table-dataTable.sortDescending=true/).
