### ISSUE TITLE
Investigate initial editorial community page structure

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#132]
The about page content for each editorial community should follow the same structure, to enable users to easily compare like-for-like.

We should come up with an initial structure based on information available from each of the current communities, and iterate on this based on feedback.

**Comment by chugginselifesciences** [comment]
An early suggestion was to include a short bio and then info on review policy (or at least link to more information on review policy). This was based on the assumption that not all ECs will perform reviews in the same way, and therefore users reading reviews might want to find out more about what was done. Or perhaps explore why the review isn't structured as they might expect etc.

Might be a good starting point to test?
