### ISSUE TITLE
Add community endorsements

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#139]
### Context

A number of the communities we have approached to engage with the application have a requirement for us to support an additional level of endorsement over and above the reviews they provide, although this looks slightly different for each:

- A number of preprints reviewed by eLife will eventually be published in the journal
- Peer Community In lists 'recommended' preprints on their webpages
- Review Commons provides reviews for preprints which may be subsequently published in a journal

We hypothesise that these endorsements or recommendations from recognised communities will in turn build additional reader trust in the articles themselves.

This work only encompasses the reader experience, and we will address the editorial community experience at a later time.

### User Stories

As a reader, I would like to know when an editorial community I trust has indicated that an article is of high scientific quality so that I can be more assured I am investing my reading time wisely.

### Slices of work

See user story map: https://miro.com/app/board/o9J_ksVfD4E

### Error conditions

- When an endorsement cannot be fetched?

### Questions

Should a community be able to endorse an article they have not reviewed? e.g. Review Commons use case, where endorsement equates to an external journal publication.

Can we use Plaudit?

**Comment by chugginselifesciences** [comment]
Does this rely on authentication?

**Comment by giorgiosironi** [comment]
Clarified to be via configuration of the application like we do for populating the reviews, so not requiring authentication.
