### ISSUE TITLE
Can we obtain the number of Disqus comments from bioRxiv?

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#145]
### Context

_As a reader, I want to know how much discourse there is around an article before I read it, so that I can make a more informed choice about which work to invest my time in._

Hypothesis: bioRxiv comments are interpreted by researchers as a lightweight form of peer review, so more discourse around an article indicates higher value and therefore commands greater trust.

### DoD

The number of bioRxiv comments should be returned alongside the article title and authors in a list of returned search results.

If there are no comments, return nothing

If there are a number of comments, return '1 comment' '2 comments' etc.

**Comment by giorgiosironi** [comment]
The [Biorxiv API](https://api.biorxiv.org/details/biorxiv/10.1101/339747) doesn't have this information, as expected.

**Comment by giorgiosironi** [comment]
[Example with 11 comments](https://www.biorxiv.org/content/10.1101/2020.05.11.089896v1?versioned=true).

**Comment by giorgiosironi** [comment]
[Disqus index page](https://disqus.com/home/forums/biorxivstage/) with predictable URLs.

**Comment by giorgiosironi** [comment]
![Screenshot_2020-06-05 API - Disqus](https://user-images.githubusercontent.com/160299/83869615-c096f000-a724-11ea-8204-27114c4bf0ca.png)

**Comment by thewilkybarkid** [comment]
```shell
curl -v "https://disqus.com/api/3.0/threads/list.json?api_key=[API_KEY]&forum=biorxivstage&thread=link:https://www.biorxiv.org/content/10.1101/2020.05.11.089896v1" | jq ".response[0].posts"
```
