### ISSUE TITLE
Display names of endorsing communities in list of search results

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#146]
### Context

_As a reader, I want to know if an article has been endorsed or not before I read it, so that I can be more informed when deciding if an article is worth my time._

We hypothesise that endorsements from trusted editorial communities are an important trust indicator for readers and that articles with one or more endorsements will command greater levels of trust.

### DoD

- [x] A clear indication of the names of communities that have endorsed an article in the list of returned results

- [x] If an article has not been endorsed by a community, return nothing.

**Comment by giorgiosironi** [comment]
Will be testing on http://localhost:8080/articles?query=Marine+cyanolichens+from+different+littoral+zones as the first article being endorsed by PeerJ.

**Comment by giorgiosironi** [comment]
To see both endorsed and not endorsed articles: http://localhost:8080/articles?query=distinct%20bacterial
