### ISSUE TITLE
Add name of endorsing community to the article page

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#148]
### Context

_As a reader, I want to know which editorial community has endorsed an article before I read it, so that I can be better informed when choosing whether or not the article is worth my time._

Hypothesis: The name of an editorial community is an important trust indicator for readers, and if a trusted editorial community has endorsed an article, it commands greater levels of trust from its readers.

### DoD

- [ ] For articles that have been endorsed, display the name of the editorial community that has endorsed them on the article page.

**Comment by thewilkybarkid** [comment]
Use search-result-style labels above the content.

**Comment by thewilkybarkid** [comment]
Hard-coded endorsement now on http://prc-staging.libero.pub/articles/10.1101/209320
