### ISSUE TITLE
Add list of endorsed articles on the editorial community pages

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#150]
### Context

_As a reader, I want to see a complete list of all the articles that have been endorsed by a community that I trust, so that I can make more informed decisions about which articles are worth my time._

Hypothesis: Readers refer to lists of content curated by editorial communities that they trust to discover the latest developments in their field of expertise.

### DoD

- [x] A second list of articles on all editorial community pages displays the articles they have endorsed.

- [x] Clicking on the title of an article redirects to the article page.

**Comment by giorgiosironi** [comment]
Question: if a community has not endorsed any article yet, current behavior is to show no heading and no (empty) list, hence no content at all. Should it say "This community hasn't endorsed any articles (yet)" or similar?

/cc @hdrury1

**Comment by hdrury1** [comment]
> Question: if a community has not endorsed any article yet, current behavior is to show no heading and no (empty) list, hence no content at all. Should it say "This community hasn't endorsed any articles (yet)" or similar?
> 
> /cc @hdrury1

I think we're fine to continue with no content for now.
