### ISSUE TITLE
Display bioRxiv comments count in article page

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#152]
### Context

_As a reader, I want easy access to the discourse around an article to help inform my interpretation of the work._

### DoD

- [x] An indication of the number of Disqus comments on the article page
- [x] A link to the bioRxiv article version 1

**Comment by giorgiosironi** [comment]
Question: what should the order of the lozenges `review`, `comments` and `endorsements` be? This to be kept consistent across the search result and the article page. /cc @hdrury1

**Comment by davidcmoulton** [comment]
> Question: what should the order of the lozenges `review`, `comments` and `endorsements` be? This to be kept consistent across the search result and the article page. /cc @hdrury1

Answered in standup 17th June: pending a pull in another direction, as long as the order is consistent between the search results page and the article page, what that order is doesn't matter for now.

**Comment by giorgiosironi** [comment]
Disqus console to create an API key for local testing: https://disqus.com/api/console/

**Comment by davidcmoulton** [comment]
Tried adding link to Biorxiv article comments page fragment `#disqus_thread`, but looks like the fragment isn't available at load time & is constructed by Disqus afterwards.

In case it's useful, the link code tried was:

```
      comments = `
        <a href="https://www.biorxiv.org/content/${doi.value}v1#disqus_thread">
          <div class="ui label">
            Comments
            <span class="detail">${commentCount}</span>
          </div>
        </a>
      `;
```

**Comment by giorgiosironi** [comment]
Skipping the link, as it stands. Could be expanded upon with tooltips or anything displayed on the article page.

**Comment by hdrury1** [comment]
Discussed and decided to link to bioRxiv article version 1.
