### ISSUE TITLE
Add PeerJ bioRxiv content

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#158]
We've received a list of legacy content from PeerJ that they are happy for us to add to the site:

https://docs.google.com/spreadsheets/d/1xQVw2YLhDM_84AGynEyqVWCww7sCEIdwgPRpGMwM5TM/edit?usp=sharing

- [x] Make review description optional

**Comment by BlueReZZ** [comment]
Does the bioRxiv content just work via datacite?

No, it gives you back a response but it has a default date and it's doi in the payload

Does the bioRxiv content work via crossref?

No, but you do get some information back:

```
"_ids": {
                    "><": 0,
                    "http://dx.doi.org/10.7287/peerj.5243v0.1/reviews/2": 1,
                    "http://prismstandard.org/namespaces/basic/2.1/doi": 2,
                    "\"10.7287/peerj.5243v0.1/reviews/2\"": 3,
                    "http://purl.org/dc/terms/creator": 4,
                    "http://id.crossref.org/contributor/g-dantas-32zwul0gtwroo": 5,
                    "http://purl.org/dc/terms/date": 6,
                    "\"2018-07-20\"^^http://www.w3.org/2001/XMLSchema#date": 7,
                    "http://purl.org/dc/terms/identifier": 8,
                    "http://purl.org/dc/terms/publisher": 9,
                    "\"PeerJ\"": 10,
                    "http://purl.org/dc/terms/title": 11,
                    "\"Peer Review #2 of \"Cross-species screening of microsatellite markers for individual identification of snow petrel Pagodroma nivea and Wilson's storm petrel Oceanites oceanicus in Antarctica (v0.1)\"\"": 12,
                    "http://purl.org/ontology/bibo/doi": 13,
                    "http://www.w3.org/2002/07/owl#sameAs": 14,
                    "doi:10.7287/peerj.5243v0.1/reviews/2": 15,
                    "info:doi/10.7287/peerj.5243v0.1/reviews/2": 16,
                    "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": 17,
                    "http://xmlns.com/foaf/0.1/Person": 18,
                    "http://xmlns.com/foaf/0.1/familyName": 19,
                    "\"Dantas\"": 20,
                    "http://xmlns.com/foaf/0.1/givenName": 21,
                    "\"G\"": 22,
                    "http://xmlns.com/foaf/0.1/name": 23,
                    "\"G Dantas\"": 24
                },
```

**Comment by BlueReZZ** [comment]
We have option to just display the author name, title and a link.
We'd still need to group each PeerJ "review" as a single PRC "review"

**Comment by thewilkybarkid** [comment]
> We'd still need to group each PeerJ "review" as a single PRC "review"

Do we? There's no limit on number of reviews by an EC yet.

**Comment by BlueReZZ** [comment]
> > We'd still need to group each PeerJ "review" as a single PRC "review"
> 
> Do we? There's no limit on number of reviews by an EC yet.

There's no technical limitation but saying something has 3 reviews for PeerJ would not be equivalent to saying the same for eLife or PREReview for example, where they would have 3 but listed as 1. If we're expecting people to apply value to number of reviews on an article this would be misleading - unless we change that for the others though... needs a discussion.

**Comment by hdrury1** [comment]
The simplest way of adding PeerJ content initially would be to list each review separately, without considering the version of the article they cover. 

However, this conflates two understandings of the word 'review': is it

- The complete output of one editorial communities' peer review process (which may include comments from one or more different reviewers)

or

- The comments from a single referee reviewing an article at the behest of an editorial community

I'm unsure if supporting both concepts is useful or desired behaviour. If we are operating under the hypothesis that an article with more reviews garners more trust, then we could be skewing this mental model for a reader.

**Comment by thewilkybarkid** [comment]
We have review data for PeerJ now, but can't access the review content itself (to be investigated in #163). The date given to Crossref is the date the article was published, which is presumably the date the review was published. _However_, the date on the review is Sep 13, 2013 (https://peerj.com/articles/190/reviews/#version-0-1-review-2). Presumably this could also be sourced through the PeerJ API.

<img width="361" alt="Screenshot 2020-06-08 at 11 34 28" src="https://user-images.githubusercontent.com/1784740/84021186-08fc1b00-a97c-11ea-8f80-57a229e33b2c.png">
