### ISSUE TITLE
Can we obtain content from Hypothesis page notes?

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#160]
eLife and Review Commons embed their bioRxiv article reviews as page notes via the Hypothesis integration:

https://via.hypothes.is/https://www.biorxiv.org/content/10.1101/2020.03.23.004002v1#annotations:6IjlyqQMEeqdDA-rdBDY-w

Is it possible to import this into the application?

All of eLife's Hypothesis content is accessible here:

https://hypothes.is/groups/q5X6RWJ6/elife

All of Review Commons' Hypothesis content is accessible here:

https://hypothes.is/groups/NEGQVabn/review-commons

# Questions to answer
- [x] What is a reliable identifier?
- [x] Can we separate a review summary from the reviews? Or can we "nest" reviews inside their summary?
- [x] What is the HTML like, can we use it as-is?
- [x] Is there a reliable feed to poll/watch/listen for new content?
- [x] Is there any versioning and what does it look like?

**Comment by thewilkybarkid** [comment]
Annotations have a simple string identifier:

```
curl https://api.hypothes.is/api/annotations/6IjlyqQMEeqdDA-rdBDY-w | jq .
{
  "id": "6IjlyqQMEeqdDA-rdBDY-w",
...
```

**Comment by thewilkybarkid** [comment]
Content is Markdown (which?). Need to find out if they strip HTML.

**Comment by thewilkybarkid** [comment]
The annotated URI is the bioRxiv URI, not a DOI:

```
curl https://api.hypothes.is/api/annotations/6IjlyqQMEeqdDA-rdBDY-w | jq .
{
...
  "uri": "https://www.biorxiv.org/content/10.1101/2020.03.23.004002v1",
```

**Comment by giorgiosironi** [comment]
At the Domain Model level, `reviewDoi` in `ReviewReference`:
- needs to change its name
- needs a discriminant (type field, or its own type) to differentiate between the Crossref and Hypothes.is cases

**Comment by giorgiosironi** [comment]
For eLife reviews, we are only interested in representing the eLife editor-written summary (first of 4 annotations) rather than all 4.

PeerJ not conforming yet to this model, we shouldn't be representing all of the reviews.

We are missing a domain concept that differentiates between the editorial community review and the individual reviews (e.g. 3) that can be done by individuals in that community.

**Comment by giorgiosironi** [comment]
Example of 3 independent reviews but no summary (a la PeerJ): https://www.biorxiv.org/content/10.1101/2020.04.17.045971v1#

**Comment by giorgiosironi** [comment]
Some eLife articles may have only a summary but not the 3 independent reviews: https://www.biorxiv.org/content/10.1101/629618v2#

**Comment by giorgiosironi** [comment]
On the model for reviews: no agreement yet on the spectrum between "review activity" (including individual review, their summary from an editor, replies from authors, perhaps even Disqus comments) or representing everything as specific concepts.

**Comment by giorgiosironi** [comment]
Hypothes.is annotations (like Disqus comment) appear to be related to a single version:
```
 "uri": "https://www.biorxiv.org/content/10.1101/2020.03.23.004002v1",
```
(potentially this could be changed by the entity that creates the annotations to encompass multiple versions)

**Comment by giorgiosironi** [comment]
At the moment we have a `ReviewReference` model that links an article version DOI to a review DOI.

By expanding the review DOI to a Hypothes.is identifier, we could represent any of these options:
- just the editorial summary from the eLife editor (this is what we seem to be doing now for the 10 eLife reviews on the PRC platform)
- represent just the 3 (anonymous?) individual reviews, as coming from the `eLife` editorial community. We do this (temporarily?) for PeerJ ad they have no summary.
- represent all 4 of these entities, without a clear differentiation.

Additional modeling (and state) would be needed to represent these entities, for example differentiating between the editorial summary and the individual reviews or linking them to each other.

This could be done with:

- state represented in the PRC application (added to the form for adding a review)?
- `tags` on the Hypothes.is annotation?

**Comment by thewilkybarkid** [comment]
Hypothes.is seem to be developing a [real-time API](https://h.readthedocs.io/en/latest/api/realtime/), but lacks documentation and seems unstable.

Crossref event data might help, but unclear if there's also real-time feeds there.

Polling is the fall-back for both.
