### ISSUE TITLE
Display most recent activity on homepage

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#169]
Rather than displaying most recent reviews, the feed on the homepage should show most recent activity within the application.

### DoD

- [x] Title of feed is '~Most~ recent activity'
- [ ] Display reviews as 'Review of `article title` added by `editorial community`'
- [ ] Display endorsements as 'Endorsement of `article title` added by `editorial community`'
- [ ] Feed is ordered by most recent events

**Comment by giorgiosironi** [comment]
Road we want to take: change the test to cover HTML output via content checks (and regexes), to abstract away more of the view model. Then add endorsements via test-driving.

**Comment by hdrury1** [comment]
Closing pending pull from users - what would be useful on the homepage?
