### ISSUE TITLE
The list of eLife endorsements is always out of date

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#171]
## Spike
- [x] Can we determine if a bioRxiv article has been published by eLife? Yes.

## Implementation
- [x] create a manual script that returns bioRxiv articles published by eLife
- [x] update bootstrap manually
- [x] ensure editorial community page doesn't break by removing lists and counting reviews and endorsements

This could be automated if manually updating becomes onerous.

**Comment by thewilkybarkid** [comment]
Looked at Europe PMC's search as they have the data, but can't see a way to query for it.

**Comment by thewilkybarkid** [comment]
DOI metadata doesn't contain it.

```
curl -v https://doi.org/10.1101/856153 -H "Accept: application/vnd.crossref.unixref+xml" -L
```

**Comment by thewilkybarkid** [comment]
The bioRxiv article page calls https://connect.biorxiv.org/bx_pub_doi_get.php?doi=10.1101/856153 which contains the information.

**Comment by thewilkybarkid** [comment]
As far as I'm aware, eLife wants to start recording articles that were preprints, but don't know if it will be back-dated.

bioRxiv seem to have the information (no idea if it's complete or not), but isn't available for querying.

**Comment by thewilkybarkid** [comment]
```
curl -v https://doi.org/10.7554/eLife.53445 -H "Accept: application/vnd.crossref.unixref+xml" -L
```

contains a URL to eLife's JATS XML, which can be used to fetch the decision letter.

**Comment by thewilkybarkid** [comment]
PeerJ review DOIs contain a link to the PeerJ article (_not_ bioRxiv):

```
curl -v https://doi.org/10.7287/peerj.4898v0.1/reviews/1 -H "Accept: application/vnd.crossref.unixref+xml" -L
```

but not from the PeerJ article to the review:

```
curl -v https://doi.org/10.7717/peerj.4898 -H "Accept: application/vnd.crossref.unixref+xml" -L
```
