### ISSUE TITLE
Allow users to subscribe to mailing list

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#172]
URL for Mailchimp form:

`http://eepurl.com/g7qqcv`

### Definition of Ready
- [x] Mail Chimp code snippet in ticket up to date
- [x] New page title specified
- [x] About page content update specified
- [x] New page content specified

### DoD

- [x] Update text on the About page
- [x] Add a link to the Mailchimp form from the About page
- [x] Add a link to the Mailchimp form in the global nav, link text "Give us feedback"
- [x] Style the global nav link to be stand out from the other links

**Comment by hdrury1** [comment]
Content for New page:

### Give us feedback and stay up-to-date

Like what you see? Want to see more? 

We’re adding value to the application on a daily basis, so sign up below to be the first to hear about the latest updates and let us know if you’re happy to be contacted about future testing opportunities.

Got something to say?

Everything we build is for researchers just like you, but we can’t do that without your feedback! How can we help you achieve your goals? Drop us a message at prc-feedback@elifesciences.org. We read your ideas every day.

**Comment by hdrury1** [comment]
Content for About page:

### How to give us feedback

The application is changing on a daily basis. To stay up-to-date as well as letting us know what you think so far, head on over to our [feedback] page.

**Comment by davidcmoulton** [comment]
> We’re adding value to the application on a daily basis, so sign up below to be the first to hear about the latest updates and let us know if you’re happy to be contacted about future testing opportunities.

@hdrury1 Is it worth having something indicative of the rough frequency of emails? It sounds like if I signed up I'd get an email every day with that day's changes documented.

**Comment by hdrury1** [comment]
> @hdrury1 Is it worth having something indicative of the rough frequency of emails? It sounds like if I signed up I'd get an email every day with that day's changes documented.

I've added words to this effect- what do you think?

**Comment by hdrury1** [comment]
Following discussions, I've created a Mailchimp form page, meaning we don't need to create a new page of our own.
