### ISSUE TITLE
Investigate using Squid

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/prc#181]
- [x] Caching
- [x] Request collapsing
- [x] Request logging
- ~Circuit breaking~
...

**Comment by giorgiosironi** [comment]
Seen errors while loading the homepage such as:
```
Error: getaddrinfo EAI_AGAIN data.crossref.org
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
```
which is a 5-second DNS timeout. Squid may help retrying these requests in-process.

**Comment by thewilkybarkid** [comment]
Proxy could be explicit (i.e. client is configured to use it), or transparent (either in the code, like [`global-agent`](https://www.npmjs.com/package/global-agent), or [at the container level](https://docs.docker.com/network/proxy/#set-the-environment-variables-manually)).

Quite a few existing containers out there, [`sameersbn/squid`](https://hub.docker.com/r/sameersbn/squid) seems to be the most used. But, most don't handle SSL.

Tried to proxy HTTPS over HTTP, but couldn't get it to work (see also https://github.com/axios/axios/issues/925).

Tried to proxy HTTPS (see https://wiki.squid-cache.org/Features/SslPeekAndSplice), but couldn't get that to work. Tried a few different containers that have been built with the `--with-openssl` flag, but didn't seem to be in a great state. Last one I was trying is [`wrouesnel/docker-squid4`](https://hub.docker.com/r/wrouesnel/docker-squid4).

Found very little documentation available, and all quite confusing.

Have since found https://www.reddit.com/r/sysadmin/comments/a67hly/squid_proxy_a_short_guide_forward_transparent/, which looks a bit more useful.

**Comment by thewilkybarkid** [comment]
Result of spike in https://github.com/libero/prc/tree/spike/squid.

Axios is configured to go through the proxy, and does:

```
1594823228.243    156 172.17.0.1 TCP_MISS/302 1020 GET https://doi.org/10.1101/2020.05.07.082263 - HIER_DIRECT/172.67.72.147 text/html
1594823228.926    213 172.17.0.1 TCP_MISS/403 538 GET https://disqus.com/api/3.0/threads/list.json? - HIER_DIRECT/151.101.64.134 application/json
1594823228.954      0 172.17.0.1 TCP_MEM_HIT/302 866 GET https://doi.org/10.1101/2020.05.07.082263 - HIER_NONE/- text/html
1594823230.033    760 172.17.0.1 TCP_MISS/200 4631 GET https://api.hypothes.is/api/annotations/5mwM1rx7EeqzN7Pt8yHgLA - HIER_DIRECT/104.22.54.159 application/json
1594823230.221    948 172.17.0.1 TCP_MISS/200 3485 GET https://api.hypothes.is/api/annotations/mGAytLx8Eeqj_n9ROen6Jw - HIER_DIRECT/104.22.54.159 application/json
1594823230.231    958 172.17.0.1 TCP_MISS/200 3266 GET https://api.hypothes.is/api/annotations/z9syOrx7EeqH_9uImmUNWA - HIER_DIRECT/104.22.54.159 application/json
```

_However_, it doesn't use the proxy details when following redirects (hence some requests missing there).

We tried configuring it to trust the certificate generated for Squid too, but it didn't work (i.e. requests succeed when they should reject an untrusted certificate).

We also used [`global-agent`](https://github.com/gajus/global-agent), which worked, except that it doesn't currently check the certificate either. This is fixed in https://github.com/gajus/global-agent/pull/27, but there doesn't appear to be a way to globally set the certificate (i.e. has to be done when making the request, which would override it entirely).

We tried using [`sameersbn/squid`](https://hub.docker.com/r/sameersbn/squid) again to avoid having our own container, but Squid appears to be unable to make HTTPS requests entirely without being built with `--enable-openssl`.

Outcome:

- Seems possible, but complicated.
- Probably want to replace Axios, and configure some other client to always use a proxy and trust the Squid certificate.
- Not looked into request collapsing; Crossref appear not to set any cache headers which means lots of requests still made. Hypothes.is do use ETags, so caching does happen there.

**Comment by thewilkybarkid** [comment]
To use certificate trusting using cURL:

```sh
curl -v -x localhost:3128 https://elifesciences.org
```

fails with

```
*   Trying ::1:3128...
* TCP_NODELAY set
* Connected to localhost (::1) port 3128 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to elifesciences.org:443
> CONNECT elifesciences.org:443 HTTP/1.1
> Host: elifesciences.org:443
> User-Agent: curl/7.65.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate in certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

But trusting the Squid certificate:

```sh
curl -v -x localhost:3128 https://elifesciences.org --cacert $(pwd)/squid/squid.crt
```

succeeds:

```
* allocate connect buffer!
* Establish HTTP proxy tunnel to elifesciences.org:443
> CONNECT elifesciences.org:443 HTTP/1.1
> Host: elifesciences.org:443
> User-Agent: curl/7.65.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /Users/chris/projects/libero/prc/squid/squid.crt
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* CONNECT phase completed!
* CONNECT phase completed!
{ [5 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [89 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3755 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [589 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=elifesciences.org
*  start date: Jul 15 10:53:07 2020 GMT
*  expire date: Jul 15 10:53:07 2021 GMT
*  subjectAltName: host "elifesciences.org" matched cert's "elifesciences.org"
*  issuer: C=GB; O=eLife; CN=*
*  SSL certificate verify ok.
}

[...]

< Via: 1.1 varnish, 1.1 1a43656ae7b6 (squid/4.11)
```

**Comment by thewilkybarkid** [comment]
Tried enabling https://wiki.squid-cache.org/Features/CollapsedForwarding and it works:

Without, many request happen at the same time:

```
1594824895.608    137 172.17.0.1 TCP_MISS/302 1020 GET https://doi.org/10.1101/2020.05.14.095547 - HIER_DIRECT/104.26.9.237 text/html
1594824895.615    144 172.17.0.1 TCP_MISS/302 1020 GET https://doi.org/10.1101/2020.05.14.095547 - HIER_DIRECT/104.26.9.237 text/html
1594824895.625    154 172.17.0.1 TCP_MISS/302 1020 GET https://doi.org/10.1101/2020.05.14.095547 - HIER_DIRECT/104.26.9.237 text/html
1594824895.718    248 172.17.0.1 TCP_MISS/302 1020 GET https://doi.org/10.1101/2020.05.14.095547 - HIER_DIRECT/104.26.9.237 text/html
1594824895.721    250 172.17.0.1 TCP_MISS/302 1020 GET https://doi.org/10.1101/2020.05.14.095547 - HIER_DIRECT/104.26.9.237 text/html
```

With, only 1 request is made:

```
1594824975.606     76 172.17.0.1 TCP_MISS/302 1019 GET https://doi.org/10.1101/2020.05.14.095547 - HIER_NONE/- text/html
1594824975.606     76 172.17.0.1 TCP_MISS/302 1019 GET https://doi.org/10.1101/2020.05.14.095547 - HIER_NONE/- text/html
1594824975.606     77 172.17.0.1 TCP_MISS/302 1019 GET https://doi.org/10.1101/2020.05.14.095547 - HIER_NONE/- text/html
1594824975.606     77 172.17.0.1 TCP_MISS/302 1019 GET https://doi.org/10.1101/2020.05.14.095547 - HIER_NONE/- text/html
1594824975.606     78 172.17.0.1 TCP_MISS/302 1020 GET https://doi.org/10.1101/2020.05.14.095547 - HIER_DIRECT/104.26.9.237 text/html
```

**Comment by giorgiosironi** [comment]
My current understanding from `curl` logs:
- we connect in plain text to Squid to say `CONNECT elifesciences.org` 
- after `CONNECT`, the connection switched to a TLS
- since we have `ssl_bump bump all` (and not `splice`), this TLS is always terminated by Squid immediately and another TLS request is forwarded to the origing server. This allows Squid to look into the content of request/responses and do caching/collapsing/etc.
- the responses returned by Squid contain `Via: ...squid...` and are signed with the custom self-signed certificate, hence clients need to be passed a reference to it to trust it.

Clients need to be passed:
- an option to make sure they validate certificates if they don't already
- the custom certificate
- a HTTP (not HTTPS) proxy option with host and (standard) port 3128.
