### ISSUE TITLE
2020-07-05 404 incident

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#185]
Possible 404 returned on a page:
https://elifesciences.slack.com/archives/C011EQLKP51/p1593966076043300

- [x] `}` final characters of a stack trace are separated into their own log lines in CloudWatch
- [x] we may have a fake 404 being logged in a middleware
- [x] unhandled exceptions are logged by Koa without any time or correlation
- [x] long lines related to the same request could be correlated with a random id
- [x] `/ping` is called too often by readiness or liveness probes in Kubernetes
- [x] `/ping` may be too slow
- [x] an empty string can be returned by port defined in `fetch-crossref-article`
- [x] use our logger in xmldom
- [x] hide broken entries in the 'Recent activity' list on the homepage
- [ ] understand how `@timestamp` is created and how it differs from `@ingestionTime`, and whether we could override them with something coming from `log`

~- [ ] maybe log ip address and user agent in a GDPR compliant way~
~- [ ] we don't have Google Analytics on 404 (or any error) pages~

**Comment by thewilkybarkid** [comment]
Details of Google Analytics user IDs: https://developers.google.com/analytics/devguides/collection/gtagjs/cookies-user-id#set_user_id

(Not sure how much it would help.)

**Comment by giorgiosironi** [comment]
Change https://github.com/libero/infrastructure/blob/master/tf/modules/kubernetes_logs/cwagent-fluentd-quickstart.yaml.tpl#L318 to include `}\n` and negate it, so that those `}` end up as part of the previous log message.

**Comment by davidcmoulton** [comment]
From the [AWS Cloudwatch Logs user guide](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData-discoverable-fields.html):
> `@timestamp` contains the event timestamp contained in the log event's timestamp field. This is equivalent to the timestamp field in InputLogevent.
@ingestionTime contains the time when the log event was received by CloudWatch Logs.
...
CloudWatch Logs Insights inserts the @ symbol at the start of fields that it generates.

**Comment by giorgiosironi** [comment]
The last point on `@timestamp` could be solved as we look to a structured format in #71, but despite trawling through the configuration it wasn't clear where Fluentd takes generates that from.
