### ISSUE TITLE
Google Analytics user journey measurements

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#188]
- [x] can pages be grouped, for example editorial community pages in the Behaviour Flow?
- [x] ~are Exit Pages interesting? e.g. lots of users exiting the flow at a certain point~ see next point on outgoing links
- [x] how do we measure outgoing links to Biorxiv being clicked?
- [x] typing search terms or scrolling through the search page: can we track them with some kind of custom events and JavaScript?
- [x] should have a cookie notice?
- [x] how do we differentiate someone doing a demo from end users? Do UTM parameters help?

**Comment by davidcmoulton** [comment]
We should be able to do something around https://support.google.com/analytics/answer/7478520?hl=en to track outbound links.

**Comment by davidcmoulton** [comment]
Content Grouping for aggregating e.g. all Editorial communities: https://support.google.com/analytics/answer/2853423

**Comment by giorgiosironi** [comment]
Added a Content Grouping to test tomorrow after it has taken effect:
https://analytics.google.com/analytics/web/?authuser=1#/a167311475w233457116p219087825/admin/content-groupings/m-content-contentGroupingTable.rowShow=10&m-content-contentGroupingTable.rowStart=0&m-content-contentGroupingTable.sortColumnId=dateModified&m-content-contentGroupingTable.sortDescending=true

**Comment by giorgiosironi** [comment]
More on [events](https://support.google.com/analytics/answer/1033068):
```
    Category: "Articles"
    Action: "ClickToFullText"
    Label: "10.1101/845081"
```

**Comment by giorgiosironi** [comment]
> typing search terms or scrolling through the search page: can we track them with some kind of custom events and JavaScript?

If you can subscribe a event listener in JavaScript, you can the [send an event](https://developers.google.com/analytics/devguides/collection/gtagjs/events):

```
gtag('event', <action>, {
  'event_category': <category>,
  'event_label': <label>,
  'value': <value>
});
```

This is likely overkill for the cases mentioned here, but could be useful in other contexts.

**Comment by giorgiosironi** [comment]
Should try to use `utm_campaign` when demoes are done, so that this can be tracked separately from organic traffic:
http://prc.libero.pub/?utm_campaign=demos-to-editorial-communities
When we give out the link to a certain group of people, we can even put a separate `utm_campaign` or other parameters.

**Comment by giorgiosironi** [comment]
Assumptions I am trying to verify:
- `Campaign` in `All Pages` can be used a secondary dimension with these values
- I thought that `utm_campaign` is tracked for a whole user session (as soon as you click another internal link it wouldn't be in the URL anymore)

**Comment by giorgiosironi** [comment]
> When you add parameters to a URL, you should always use utm_source, utm_medium, and utm_campaign.

**Comment by giorgiosironi** [comment]
More like this then:
http://prc.libero.pub/?utm_source=paul-shannon-friends&utm_medium=demo&utm_campaign=psychoceramics-demo-2020-07-13

**Comment by giorgiosironi** [comment]
[List of campaigns](https://analytics.google.com/analytics/web/?authuser=1#/report/trafficsources-campaigns/a167311475w233457116p219087825/_u.date00=20200713&_u.date01=20200713/)
A [report with campaign as a secondary dimension](https://analytics.google.com/analytics/web/?authuser=1#/report/content-pages/a167311475w233457116p219087825/_u.date00=20200713&_u.date01=20200713&explorer-table.secSegmentId=analytics.campaign&explorer-table.plotKeys=%5B%5D/):
![Screenshot_2020-07-13 Analytics](https://user-images.githubusercontent.com/160299/87312724-d912db00-c518-11ea-93f1-3ebf542a6aec.png)

**Comment by giorgiosironi** [comment]
I think we [need a cookie notice](https://ico.org.uk/for-organisations/guide-to-pecr/guidance-on-the-use-of-cookies-and-similar-technologies/how-do-we-comply-with-the-cookie-rules/#comply15), that loads Google Analytics only after consent.

**Comment by giorgiosironi** [comment]
[Cookiebot report](https://github.com/libero/prc/files/4913085/report-prcliberopub-4274164.pdf)
