### ISSUE TITLE
Register hive.review domain for our AWS account

### ISSUE THREAD

**Issue by BlueReZZ** [libero/prc#195]
Given there were no objections to `hive.review` as a domain name and it leaves possibilities of calling the platform The Hive or Review Hive or something related, this seems like a good first step.

**Comment by BlueReZZ** [comment]
Due diligence on the name: https://miro.com/app/board/o9J_ksUxGvM=/?moveToWidget=3074457348873278955&cot=15

**Comment by giorgiosironi** [comment]
Noticing the Route 53 only has `.reviews` domain rather than `.review`, for $22/year. Both TLDs exists.

**Comment by giorgiosironi** [comment]
However, `hive.reviews` is taken ([unknown by whom](https://www.whois.com/whois/hive.reviews)) and it's a potential clash.

**Comment by giorgiosironi** [comment]
`.review` goes for $111 (for the first year) on GoDaddy but it's managed by a [company](http://nic.review/about.html) that [can't do HTTPS](https://nic.review/resources.html) so it looks all a bit shady.

**Comment by giorgiosironi** [comment]
To buy it somewhere else, will need credit card details which we can obtain from Vikki.

**Comment by BlueReZZ** [comment]
If you're setting up the DNS as part of this ticket, can we have the MX records set the same as for `libero.pub` so that we can use it as a Gmail alias please?

I'll create follow up tickets to create the email alias etc.

More info on Gmail MX records: https://support.google.com/a/answer/140034

**Comment by BlueReZZ** [comment]
Awaiting DNS propagation for mail to work then I'll create an admin account for DNSimple to manage the domain on `team@hive.review`
