### ISSUE TITLE
What should be shown on the Home page?

### ISSUE THREAD

**Issue by kevinrutherford** [libero/prc#35]
Possibilities include:

* articles which have requested reviews
* my favourites
* recent articles from specific servers
* recent reviews
* just a search box
* ...?

**Comment by gmaciocci** [comment]
Thankfully have a design that fully encompasses the Product requirements. This should help you focus on features that have been determined to be necessary:

https://projects.invisionapp.com/share/B9WVPQAS4PE#/screens
