### ISSUE TITLE
What are article types used for in preprints?

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#45]
In preprints almost everything is a `New Results` article. Is this correct?

**Comment by chugginselifesciences** [comment]
Before the restructure we'd planned not to include an article type selection or label until additional type are required, which has not been decided yet.

BioRxiv has `New Results`, `Confirmatory Results` and `Contradictory Results`, which makes sense to indicate to readers. And I also imagine we could see value in something similar to `short reports` to indicate that it's not as complete as the default type. Also perhaps allowing a separate type for new `methods` or protocols in future could be useful.

All speculation at this point though.
