### ISSUE TITLE
Link from the homepage to a Google Doc with implemented scenarios, in progress scenarios, questions

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#57]

**Comment by giorgiosironi** [comment]
@hdrury1 to provide current content first, avoiding the developer's point of view.

**Comment by hdrury1** [comment]
Happy for the platform to link out to this document:

https://docs.google.com/document/d/1sKjhRy55kLaNv3a4vK1PsEPTFfivKbJRvJPwNx0HOS4/edit?usp=sharing

**Comment by hdrury1** [comment]
Happy for the platform to link out to this document:

https://docs.google.com/document/d/1sKjhRy55kLaNv3a4vK1PsEPTFfivKbJRvJPwNx0HOS4/edit?usp=sharing
