### ISSUE TITLE
Group article page code into one place

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/prc#58]
Refactor the code behind the article page (eg middleware, template, fetcher) so that it's grouped together in one place.

## Checklist

- [x] Encapsulate `article-page` middleware in `src/article-page/middleware`
- [x] Encapsulate `article-page` templates in `src/article-page/templates`
- [x] Encapsulate `test/handlers` specific tests in `test/article-page`
- [x] Encapsulate `types/*` that are used only in `article-page`
- [x] Rename types that are used from fetchers so that they don't look like they are used only in `article-page`
- [x] Remove unused `types/*`
- ~[ ] Should the `src/api` folder be `src/adapters`?~
- [x] Wait on https://github.com/libero/prc/issues/55 to see where `types/article` ends up

**Comment by giorgiosironi** [comment]
For now just moving files into subfolders, but they may get some simplified names that avoid the `article-page` prefix/suffix due to the namespacing provided by the subdomain.
