### ISSUE TITLE
Define what launch means

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#70]
@hdrury1 @chugginselifesciences

**Comment by hdrury1** [comment]
We have settled upon two different aims for launch:

1. To attract support from additional Editorial Communities to help grow engagement in the platform and build trust in review content.

2. To garner initial, qualitative feedback from a limited group of select users. We currently anticipate this group will contain researchers that Chris and I have already made contact with, but may additionally include Mike Eisen and members of eLife's editorial leadership sympathetic to the vision.
