### ISSUE TITLE
Fill in unit tests missing from middleware refactoring

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#73]
Middleware (and some repositories possibly) are covered by integration tests in `test/handlers` where they exist. They should be unit tested in isolation which should greatly simplify covering their state space with respect to having to test the whole route for each case.

Code coverage measurement could help here? Not used as a target but as a discovery tool.

**Comment by kevinrutherford** [comment]
The following bash command lists the source files that have no corresponding test file:

`comm -23 <( find src -type f | sort | uniq ) <( find test -type f | sed -e 's/^test/src/' -e 's/\.test//' | sort | uniq )`
