### ISSUE TITLE
Specify order of reviews

### ISSUE THREAD

**Issue by giorgiosironi** [libero/prc#8]
Affects article pages and index.

**Comment by gmaciocci** [comment]
Reviews on the article should be displayed in reverse chronological order. See here: 

https://projects.invisionapp.com/share/B9WVPQAS4PE#/screens/415053755

On the home page, the counter of total reviews is shown for each listing, alongside the latest review only: 

https://projects.invisionapp.com/share/B9WVPQAS4PE#/screens/415097280
