### ISSUE TITLE
Fetch article abstract from Crossref proprietary format

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#82]
We should display the article's abstract as well as its title, author and date information.

The abstract is an important factor in the reader's decision whether or not the article is relevant and of importance to them, and therefore if they should continue reading the whole preprint.

**Comment by giorgiosironi** [comment]
Test with http://localhost:8080/articles/10.1101/339747 as it's an article we don't have in the hardcoded map of abstracts so will trigger loading from the API.

**Comment by giorgiosironi** [comment]
How to produce new XML for a unit test of `fetchAbstractFromCrossref`:
```
curl -v -L -H "Accep/vnd.crossref.unixref+xml" "https://doi.org/10.1101/642017"
```
