### ISSUE TITLE
Markdown summary to replace/compliment About document

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#85]
Key points from the 'About the PRC platform' and 'From A to PRC' documents should be captured and input into markdown that is committed to the repo. 

The purpose of this documentation will be for additional context and a smoother user experience than the current journey to a Google doc.

/cc @BlueReZZ 

[ ] Convert existing doc using stencila convert; store in `/static/about.md`
~~[ ] Update doc with a better structure and information from the two docs named above~~
[ ] Replace the About link in the nav to a web page that displays the markdown, converted to HTML

**Comment by BlueReZZ** [comment]
Two tasks:

- Convert existing doc using `stencila convert`
- Update doc with a better structure and information from the two docs named above

**Comment by BlueReZZ** [comment]
Separated the task to update the about page with better content to a new ticket in #96 so this ticket can be closed when @kevinrutherford is happy with the tests.
