### ISSUE TITLE
Style a reviewed article list item

### ISSUE THREAD

**Issue by davidcmoulton** [libero/prc#90]

**Comment by chugginselifesciences** [comment]
Can we get the subject area/MSA equivalent from BioRxiv DOIs? Could be useful to users to see on listings and article page/in content header.

**Comment by chugginselifesciences** [comment]
Potential styling shown on home page:

![image](https://user-images.githubusercontent.com/41907215/82432861-8a9d0f00-9a88-11ea-85e5-378a00e3c439.png)

**Comment by chugginselifesciences** [comment]
On EC page:
![image](https://user-images.githubusercontent.com/41907215/82432941-a1dbfc80-9a88-11ea-8cbf-198e7fe47015.png)
