### ISSUE TITLE
Change home page title to "Untitled Publish Review Curate Platform"

### ISSUE THREAD

**Issue by chugginselifesciences** [libero/prc#95]
Not sure if this was agreed, but could be worth replacing `PRC` on home page with a clearer placeholder name.

Could do with increased padding etc.

**Comment by hdrury1** [comment]
I've scheduled a meeting for Thursday to discuss branding, but this would be a good interim placeholder.

**Comment by giorgiosironi** [comment]
I assume this also cover the `<title>` for every page, which currently is `PRC` too.

**Comment by giorgiosironi** [comment]
Available in [staging](http://prc-staging.libero.pub/).
