### ISSUE TITLE
Add PREreview reviews 

### ISSUE THREAD

**Issue by hdrury1** [libero/prc#97]
10.5281/zenodo.3678326 [Article DOI 10.1101/833392]
10.5281/zenodo.3749854 [Article DOI 10.1101/2020.03.28.013177]
10.5281/zenodo.3756962 [Article DOI 10.1101/2020.03.22.002386]
10.5281/zenodo.3756966 [Article DOI 10.1101/2020.02.26.966986]
10.5281/zenodo.3832925 [Article DOI 2020.01.22.915660]
10.5281/zenodo.3672787 [Article DOI 10.1101/861799]
10.5281/zenodo.3702901 [Article DOI 10.1101/862755]
10.5281/zenodo.3718438 [Article DOI 10.1101/845081]
10.5281/zenodo.3678334 [Article DOI 10.1101/823989]
10.5281/zenodo.3662409 [Article DOI 10.1101/380238]

## Checklist

Depends on #98 

- [x] add ReviewReferences
- [ ] decide which `added` date to use
- [x] hardcode abstracts

**Comment by giorgiosironi** [comment]
[Some of the abstracts have footnotes](http://prc-staging.libero.pub/articles/10.1101/2020.02.26.966986#ref-5) which won't link to anything.

**Comment by giorgiosironi** [comment]
Right now all articles are added in the bootstrap of the application with the same fixed date.

**Comment by giorgiosironi** [comment]
The review summaries look [wonky](http://prc-staging.libero.pub/articles/10.1101/845081) as expected.

Reopen if the dates become a problem.

**Comment by hdrury1** [comment]
I've added #99 to To Do. I think it's enough to truncate for now, and we can look at fancier tidies later.
